site_name: LiR Documentation
repo_url: https://github.com/NetherlandsForensicInstitute/lir
repo_name: LiR
edit_uri: edit/main/docs/
site_dir: docs_html
theme:
  name: readthedocs
plugins:
  - macros:
      module_name: mkdocs
