name: Test package

on:
  push:
    branches: ['main']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Linting, formatting, static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
          cache: true
          cache-dependency-path: 'pdm.lock'
      - name: Check lock file
        run: pdm lock --check
      - name: Install necessary dependencies
        run: pdm sync --group dev
      - name: Run checks
        run: pdm run check
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        python-version: ['3.12', '3.14']  # Check oldest and newest python version
    steps:
      - uses: actions/checkout@v5
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: 'pdm.lock'
      - name: Install necessary dependencies
        run: pdm sync --group dev
      - name: Run tests
        run: pdm run test
